# Use the official Python 3.10 image based on Alpine Linux for a lightweight environment
FROM python:3.10-alpine

# Add the myapp.py file from the local directory to the root of the container's filesystem
ADD myapp.py .

# Set the default command to run myapp.py using Python
CMD ["python", "./myapp.py"]
